apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-worker
  labels:
    app: email-worker
spec:
  replicas: 1 # 기본적으로 1개를 띄우지만, 곧 KEDA가 이 숫자를 조종하게 됩니다.
  selector:
    matchLabels:
      app: email-worker
  template:
    metadata:
      labels:
        app: email-worker
    spec:
      containers:
      - name: worker
        image: my-python-worker:latest # (나중에 우리가 파이썬 코드를 도커로 구울 때 쓸 이름입니다)
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: AWS_DEFAULT_REGION
          value: "ap-northeast-2"
        # 로컬스택과 통신하기 위한 환경 변수 세팅
        - name: AWS_ENDPOINT_URL
          value: "http://localstack-service.default.svc.cluster.local:4566"
