apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
spec:
  scaleTargetRef:
    name: email-worker # 위에서 만든 deployment.yaml의 이름과 똑같아야 KEDA가 누구를 늘릴지 알 수 있습니다.
  minReplicaCount: 0   # ★ Scale-to-Zero: 큐에 메시지가 하나도 없으면 워커를 0개로 소멸시킵니다!
  maxReplicaCount: 10  # 트래픽이 폭주해도 최대 10개까지만 늘어나도록 방어선을 칩니다.
  triggers:
  - type: aws-sqs-queue
    metadata:
      # KEDA가 감시할 SQS 큐의 주소 (로컬스택 기준)
      queueURL: "http://localstack-service.default.svc.cluster.local:4566/000000000000/resale-email"
      # 메시지가 5개 쌓일 때마다 워커를 1개씩 추가 투입하라는 기준점
      queueLength: "5" 
      awsRegion: "ap-northeast-2"
