apiVersion: v1
kind: Service
metadata:
  name: redis-counter-master
  namespace: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-counter
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-counter-master
  namespace: redis
spec:
  serviceName: redis-counter-master
  replicas: 1
  selector:
    matchLabels:
      app: redis-counter
  template:
    metadata:
      labels:
        app: redis-counter
    spec:
      containers:
      - name: redis
        image: redis:7-alpine  # 가볍고 안정적인 공식 이미지
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-counter-secret
              key: password
        command: ["sh", "-c", "redis-server --appendonly yes --appendfsync everysec --requirepass $(REDIS_PASSWORD)"] # AOF 설정 + 비밀번호 인증
