prometheus:
  url: http://kube-prom-kube-prometheus-prometheus.monitoring.svc
  port: 9090

rules:
  default: false
  custom:
    - seriesQuery: 'ws_active_connections{namespace="realtime"}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          service:
            resource: "service"
      name:
        matches: "ws_active_connections"
        as: "ws_active_connections_total"
      metricsQuery: 'sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)'
