apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: realtime-ws
  namespace: realtime
  labels:
    release: kube-prom
spec:
  selector:
    matchLabels:
      app: realtime-ws
  namespaceSelector:
    matchNames:
      - realtime
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
