apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-counter-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend-counter
  namespaceSelector:
    matchNames:
      - queuing-d
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 5s
