apiVersion: v1
kind: Service
metadata:
  name: backend-counter-service
  labels:
    app: backend-counter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend-counter
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
