apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-counter-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-counter
  namespaceSelector:
    matchNames:
      # 👇 하드코딩된 'default' 대신, 헬름이 배포되는 위치를 자동으로 긁어가게 만듦!
      - {{ .Release.Namespace }}
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 5s
