apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-counter-monitor
  namespace: monitoring
  labels:
    release: monitoring   # <-- 이 부분을 다시 'monitoring'으로 변경!
spec:
  selector:
    matchLabels:
      app: backend-counter
  namespaceSelector:
    matchNames:
      - queuing-d
  endpoints:
  - port: http
    targetPort: 8080
    path: /actuator/prometheus
    interval: 5s
