replicaCount: 1

image:
  repository: dororonge/queuing-worker
  tag: "1.0.2"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
