replicaCount: 2

image:
  repository: "ttomang/backend-counter"
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  dbHost: "mariadb.queuing-db.svc.cluster.local"
  dbPort: "3306"
  redisHost: "redis-master.realtime.svc.cluster.local"
  redisPort: "6379"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      selectPolicy: Max
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
