apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-worker
  labels:
    app: email-worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: email-worker
  template:
    metadata:
      labels:
        app: email-worker
    spec:
      serviceAccountName: email-worker
      containers:
      - name: worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
        # ❌ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_ENDPOINT_URL 삭제 완료
        - name: AWS_DEFAULT_REGION
          value: "ap-northeast-2"
        - name: MYSQL_HOST
          value: "211.46.52.164"
        - name: MYSQL_PORT
          value: "13306"
        - name: MYSQL_USER
          value: "team2"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DB
          value: "queuing_db"
        resources:
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
