apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sqs-queue-scaledobject  # 파일에 맞는 이름
  namespace: default
spec:
  scaleTargetRef:
    name: queuing-worker-b
  triggers:
    - type: aws-sqs-queue
      metadata:
        awsRegion: ap-northeast-2
        queueLength: "5"
        queueURL: http://localstack.queuing-localstack.svc.cluster.local:4566/000000000000/resale-queue
      authenticationRef:
        name: keda-aws-credentials
