apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sqs-queue-scaledobject
spec:
  scaleTargetRef:
    name: email-worker # deployment.yaml의 metadata.name과 정확히 일치해야 함!
  minReplicaCount: 0   # 큐에 메시지가 없으면 0개로 소멸
  maxReplicaCount: 10  # 최대 10개까지 확장
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: "http://localstack-service.default.svc.cluster.local:4566/000000000000/resale-queue"
      queueLength: "5"  # 메시지 5개당 워커 1개 추가
      awsRegion: "ap-northeast-2"
