# templates/scaled-object.yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queuing-worker-b-scaler
spec:
  scaleTargetRef:
    name: email-worker
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: {{ .Values.aws.queueURL | quote }}
        queueLength: "5"
        awsRegion: {{ .Values.aws.region | quote }}
        identityOwner: {{ .Values.keda.identityOwner | quote }}
