apiVersion: v1
kind: Service
metadata:
  name: email-worker
  labels:
    app: email-worker
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
      nodePort: 30082
  selector:
    app: email-worker
