apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-aws-credentials
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: localstack-aws-secret
      key: awsAccessKeyID
    - parameter: awsSecretAccessKey
      name: localstack-aws-secret
      key: awsSecretAccessKey
