spring.data.redis.host=redis-counter-master.redis.svc.cluster.local
spring.data.redis.port=6379

# Actuator 설정
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Micrometer Histogram 및 레이턴시 경로 추적 설정
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.9,0.95,0.99
